# Generated by Django 3.0.9 on 2020-08-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20200813_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidades',
            old_name='habilidades',
            new_name='habilidad',
        ),
    ]
