# Generated by Django 3.0.9 on 2020-08-13 18:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20200813_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
